[package]
name = "modrust"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "sync"] }
ys1r = {git = "https://github.com/YumaYX/YS1-R"}
